[2025-04-16T21:29:35.233+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-16T21:29:35.241+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_dag.check_file_exists manual__2025-04-16T15:59:27.545650+00:00 [queued]>
[2025-04-16T21:29:35.246+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_dag.check_file_exists manual__2025-04-16T15:59:27.545650+00:00 [queued]>
[2025-04-16T21:29:35.246+0530] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-16T21:29:35.258+0530] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): check_file_exists> on 2025-04-16 15:59:27.545650+00:00
[2025-04-16T21:29:35.260+0530] {standard_task_runner.py:72} INFO - Started process 1142 to run task
[2025-04-16T21:29:35.263+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'check_dag', 'check_file_exists', 'manual__2025-04-16T15:59:27.545650+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/check_dag.py', '--cfg-path', '/tmp/tmp3u1myr88']
[2025-04-16T21:29:35.264+0530] {standard_task_runner.py:105} INFO - Job 30: Subtask check_file_exists
[2025-04-16T21:29:35.290+0530] {task_command.py:467} INFO - Running <TaskInstance: check_dag.check_file_exists manual__2025-04-16T15:59:27.545650+00:00 [running]> on host Voldemort.
[2025-04-16T21:29:35.342+0530] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='check_dag' AIRFLOW_CTX_TASK_ID='check_file_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T15:59:27.545650+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-16T15:59:27.545650+00:00'
[2025-04-16T21:29:35.343+0530] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-16T21:29:35.352+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-16T21:29:35.353+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'test -f /tmp/dummy']
[2025-04-16T21:29:35.359+0530] {subprocess.py:86} INFO - Output:
[2025-04-16T21:29:35.360+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-16T21:29:35.374+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-16T21:29:35.374+0530] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=check_dag, task_id=check_file_exists, run_id=manual__2025-04-16T15:59:27.545650+00:00, execution_date=20250416T155927, start_date=20250416T155935, end_date=20250416T155935
[2025-04-16T21:29:35.396+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-16T21:29:35.409+0530] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-16T21:29:35.413+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
