[2025-05-22T22:10:31.437+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-22T22:10:31.443+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_taxi_etl.transform_and_load manual__2025-05-22T16:40:25.210508+00:00 [queued]>
[2025-05-22T22:10:31.447+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_taxi_etl.transform_and_load manual__2025-05-22T16:40:25.210508+00:00 [queued]>
[2025-05-22T22:10:31.447+0530] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-22T22:10:31.456+0530] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): transform_and_load> on 2025-05-22 16:40:25.210508+00:00
[2025-05-22T22:10:31.458+0530] {standard_task_runner.py:72} INFO - Started process 15967 to run task
[2025-05-22T22:10:31.460+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'nyc_taxi_etl', 'transform_and_load', 'manual__2025-05-22T16:40:25.210508+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/nyc_taxi_etl.py', '--cfg-path', '/tmp/tmp5f_151e8']
[2025-05-22T22:10:31.461+0530] {standard_task_runner.py:105} INFO - Job 161: Subtask transform_and_load
[2025-05-22T22:10:31.480+0530] {task_command.py:467} INFO - Running <TaskInstance: nyc_taxi_etl.transform_and_load manual__2025-05-22T16:40:25.210508+00:00 [running]> on host Voldemort.
[2025-05-22T22:10:31.520+0530] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nyc_taxi_etl' AIRFLOW_CTX_TASK_ID='transform_and_load' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T16:40:25.210508+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-22T16:40:25.210508+00:00'
[2025-05-22T22:10:31.521+0530] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-22T22:10:31.533+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-22T22:10:31.534+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/opt/spark/bin/spark-submit /home/pranav_shirali/airflow-project/scripts/ETL/transform_and_load.py']
[2025-05-22T22:10:31.538+0530] {subprocess.py:86} INFO - Output:
[2025-05-22T22:10:33.353+0530] {subprocess.py:93} INFO - 25/05/22 22:10:33 WARN Utils: Your hostname, Voldemort resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
[2025-05-22T22:10:33.355+0530] {subprocess.py:93} INFO - 25/05/22 22:10:33 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-05-22T22:10:34.372+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO SparkContext: Running Spark version 3.5.5
[2025-05-22T22:10:34.373+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-05-22T22:10:34.373+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO SparkContext: Java version 11.0.27
[2025-05-22T22:10:34.456+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-22T22:10:34.539+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO ResourceUtils: ==============================================================
[2025-05-22T22:10:34.539+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-05-22T22:10:34.539+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO ResourceUtils: ==============================================================
[2025-05-22T22:10:34.540+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO SparkContext: Submitted application: NYC Taxi ABFSS
[2025-05-22T22:10:34.558+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-05-22T22:10:34.566+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO ResourceProfile: Limiting resource is cpu
[2025-05-22T22:10:34.566+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-05-22T22:10:34.615+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO SecurityManager: Changing view acls to: pranav_shirali
[2025-05-22T22:10:34.616+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO SecurityManager: Changing modify acls to: pranav_shirali
[2025-05-22T22:10:34.616+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO SecurityManager: Changing view acls groups to:
[2025-05-22T22:10:34.616+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO SecurityManager: Changing modify acls groups to:
[2025-05-22T22:10:34.617+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: pranav_shirali; groups with view permissions: EMPTY; users with modify permissions: pranav_shirali; groups with modify permissions: EMPTY
[2025-05-22T22:10:34.827+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO Utils: Successfully started service 'sparkDriver' on port 43911.
[2025-05-22T22:10:34.859+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO SparkEnv: Registering MapOutputTracker
[2025-05-22T22:10:34.885+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO SparkEnv: Registering BlockManagerMaster
[2025-05-22T22:10:34.901+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-05-22T22:10:34.902+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-05-22T22:10:34.905+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-05-22T22:10:34.929+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-872e98df-610d-4b04-bf49-11fcd6fb8dd2
[2025-05-22T22:10:34.940+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-05-22T22:10:34.950+0530] {subprocess.py:93} INFO - 25/05/22 22:10:34 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-05-22T22:10:35.100+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-05-22T22:10:35.156+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-05-22T22:10:35.187+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO SparkContext: Added JAR /opt/spark/jars/hadoop-azure-3.3.1.jar at spark://10.255.255.254:43911/jars/hadoop-azure-3.3.1.jar with timestamp 1747932034362
[2025-05-22T22:10:35.187+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO SparkContext: Added JAR /opt/spark/jars/azure-storage-8.6.6.jar at spark://10.255.255.254:43911/jars/azure-storage-8.6.6.jar with timestamp 1747932034362
[2025-05-22T22:10:35.187+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO SparkContext: Added JAR /opt/spark/jars/hadoop-azure-datalake-3.3.1.jar at spark://10.255.255.254:43911/jars/hadoop-azure-datalake-3.3.1.jar with timestamp 1747932034362
[2025-05-22T22:10:35.237+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO Executor: Starting executor ID driver on host 10.255.255.254
[2025-05-22T22:10:35.237+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO Executor: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-05-22T22:10:35.237+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO Executor: Java version 11.0.27
[2025-05-22T22:10:35.242+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-05-22T22:10:35.243+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@54aa6164 for default.
[2025-05-22T22:10:35.252+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO Executor: Fetching spark://10.255.255.254:43911/jars/azure-storage-8.6.6.jar with timestamp 1747932034362
[2025-05-22T22:10:35.306+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO TransportClientFactory: Successfully created connection to /10.255.255.254:43911 after 26 ms (0 ms spent in bootstraps)
[2025-05-22T22:10:35.312+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO Utils: Fetching spark://10.255.255.254:43911/jars/azure-storage-8.6.6.jar to /tmp/spark-a3286002-8abe-48cd-ae34-3978693c6db9/userFiles-45cc6e1f-fd7b-4673-b3ae-113e723578a7/fetchFileTemp3216736351830646176.tmp
[2025-05-22T22:10:35.353+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO Executor: Adding file:/tmp/spark-a3286002-8abe-48cd-ae34-3978693c6db9/userFiles-45cc6e1f-fd7b-4673-b3ae-113e723578a7/azure-storage-8.6.6.jar to class loader default
[2025-05-22T22:10:35.353+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO Executor: Fetching spark://10.255.255.254:43911/jars/hadoop-azure-datalake-3.3.1.jar with timestamp 1747932034362
[2025-05-22T22:10:35.354+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO Utils: Fetching spark://10.255.255.254:43911/jars/hadoop-azure-datalake-3.3.1.jar to /tmp/spark-a3286002-8abe-48cd-ae34-3978693c6db9/userFiles-45cc6e1f-fd7b-4673-b3ae-113e723578a7/fetchFileTemp14240489338478016521.tmp
[2025-05-22T22:10:35.358+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO Executor: Adding file:/tmp/spark-a3286002-8abe-48cd-ae34-3978693c6db9/userFiles-45cc6e1f-fd7b-4673-b3ae-113e723578a7/hadoop-azure-datalake-3.3.1.jar to class loader default
[2025-05-22T22:10:35.359+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO Executor: Fetching spark://10.255.255.254:43911/jars/hadoop-azure-3.3.1.jar with timestamp 1747932034362
[2025-05-22T22:10:35.359+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO Utils: Fetching spark://10.255.255.254:43911/jars/hadoop-azure-3.3.1.jar to /tmp/spark-a3286002-8abe-48cd-ae34-3978693c6db9/userFiles-45cc6e1f-fd7b-4673-b3ae-113e723578a7/fetchFileTemp14288015593408720916.tmp
[2025-05-22T22:10:35.366+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO Executor: Adding file:/tmp/spark-a3286002-8abe-48cd-ae34-3978693c6db9/userFiles-45cc6e1f-fd7b-4673-b3ae-113e723578a7/hadoop-azure-3.3.1.jar to class loader default
[2025-05-22T22:10:35.377+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 43725.
[2025-05-22T22:10:35.377+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO NettyBlockTransferService: Server created on 10.255.255.254:43725
[2025-05-22T22:10:35.379+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-05-22T22:10:35.386+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.255.255.254, 43725, None)
[2025-05-22T22:10:35.389+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO BlockManagerMasterEndpoint: Registering block manager 10.255.255.254:43725 with 434.4 MiB RAM, BlockManagerId(driver, 10.255.255.254, 43725, None)
[2025-05-22T22:10:35.391+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.255.255.254, 43725, None)
[2025-05-22T22:10:35.392+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.255.255.254, 43725, None)
[2025-05-22T22:10:35.930+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-05-22T22:10:35.943+0530] {subprocess.py:93} INFO - 25/05/22 22:10:35 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmpmpy9svrv/spark-warehouse'.
[2025-05-22T22:10:37.647+0530] {subprocess.py:93} INFO - 25/05/22 22:10:37 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: abfss://taxidata@tietoevryproject.dfs.core.windows.net/part.73.parquet.
[2025-05-22T22:10:37.647+0530] {subprocess.py:93} INFO - java.nio.file.AccessDeniedException: Operation failed: "The specified account is disabled.", 403, HEAD, https://tietoevryproject.dfs.core.windows.net/taxidata/?upn=false&action=getAccessControl&timeout=90
[2025-05-22T22:10:37.648+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.checkException(AzureBlobFileSystem.java:1210)
[2025-05-22T22:10:37.648+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.getFileStatus(AzureBlobFileSystem.java:509)
[2025-05-22T22:10:37.648+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1777)
[2025-05-22T22:10:37.649+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:54)
[2025-05-22T22:10:37.649+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:366)
[2025-05-22T22:10:37.649+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-05-22T22:10:37.649+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-05-22T22:10:37.649+0530] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-22T22:10:37.649+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-05-22T22:10:37.650+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:563)
[2025-05-22T22:10:37.650+0530] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-22T22:10:37.650+0530] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-22T22:10:37.650+0530] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-22T22:10:37.650+0530] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-22T22:10:37.650+0530] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-22T22:10:37.650+0530] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-05-22T22:10:37.650+0530] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-22T22:10:37.651+0530] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-22T22:10:37.651+0530] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-22T22:10:37.651+0530] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-22T22:10:37.651+0530] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-22T22:10:37.651+0530] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-22T22:10:37.651+0530] {subprocess.py:93} INFO - Caused by: Operation failed: "The specified account is disabled.", 403, HEAD, https://tietoevryproject.dfs.core.windows.net/taxidata/?upn=false&action=getAccessControl&timeout=90
[2025-05-22T22:10:37.651+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation.completeExecute(AbfsRestOperation.java:218)
[2025-05-22T22:10:37.651+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation.lambda$execute$0(AbfsRestOperation.java:181)
[2025-05-22T22:10:37.651+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDurationOfInvocation(IOStatisticsBinding.java:464)
[2025-05-22T22:10:37.652+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation.execute(AbfsRestOperation.java:179)
[2025-05-22T22:10:37.652+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.services.AbfsClient.getAclStatus(AbfsClient.java:942)
[2025-05-22T22:10:37.652+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.services.AbfsClient.getAclStatus(AbfsClient.java:924)
[2025-05-22T22:10:37.652+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.getIsNamespaceEnabled(AzureBlobFileSystemStore.java:324)
[2025-05-22T22:10:37.652+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.getFileStatus(AzureBlobFileSystemStore.java:836)
[2025-05-22T22:10:37.652+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.getFileStatus(AzureBlobFileSystem.java:507)
[2025-05-22T22:10:37.652+0530] {subprocess.py:93} INFO - 	... 20 more
[2025-05-22T22:10:37.796+0530] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-22T22:10:37.797+0530] {subprocess.py:93} INFO -   File "/home/pranav_shirali/airflow-project/scripts/ETL/transform_and_load.py", line 18, in <module>
[2025-05-22T22:10:37.797+0530] {subprocess.py:93} INFO -     df = spark.read.parquet(file_path)
[2025-05-22T22:10:37.797+0530] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 544, in parquet
[2025-05-22T22:10:37.797+0530] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-05-22T22:10:37.797+0530] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-05-22T22:10:37.798+0530] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-05-22T22:10:37.798+0530] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o30.parquet.
[2025-05-22T22:10:37.798+0530] {subprocess.py:93} INFO - : java.nio.file.AccessDeniedException: Operation failed: "The specified account is disabled.", 403, HEAD, https://tietoevryproject.dfs.core.windows.net/taxidata/?upn=false&action=getAccessControl&timeout=90
[2025-05-22T22:10:37.798+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.checkException(AzureBlobFileSystem.java:1210)
[2025-05-22T22:10:37.798+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.getFileStatus(AzureBlobFileSystem.java:509)
[2025-05-22T22:10:37.798+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1760)
[2025-05-22T22:10:37.798+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.exists(AzureBlobFileSystem.java:1038)
[2025-05-22T22:10:37.798+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4(DataSource.scala:756)
[2025-05-22T22:10:37.799+0530] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4$adapted(DataSource.scala:754)
[2025-05-22T22:10:37.799+0530] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:384)
[2025-05-22T22:10:37.799+0530] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-05-22T22:10:37.799+0530] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-05-22T22:10:37.799+0530] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-05-22T22:10:37.799+0530] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-05-22T22:10:37.799+0530] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-05-22T22:10:37.799+0530] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-05-22T22:10:37.799+0530] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-05-22T22:10:37.799+0530] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[2025-05-22T22:10:37.800+0530] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[2025-05-22T22:10:37.800+0530] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[2025-05-22T22:10:37.800+0530] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[2025-05-22T22:10:37.800+0530] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[2025-05-22T22:10:37.800+0530] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[2025-05-22T22:10:37.800+0530] {subprocess.py:93} INFO - Caused by: Operation failed: "The specified account is disabled.", 403, HEAD, https://tietoevryproject.dfs.core.windows.net/taxidata/?upn=false&action=getAccessControl&timeout=90
[2025-05-22T22:10:37.800+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation.completeExecute(AbfsRestOperation.java:218)
[2025-05-22T22:10:37.800+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation.lambda$execute$0(AbfsRestOperation.java:181)
[2025-05-22T22:10:37.801+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDurationOfInvocation(IOStatisticsBinding.java:464)
[2025-05-22T22:10:37.801+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation.execute(AbfsRestOperation.java:179)
[2025-05-22T22:10:37.801+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.services.AbfsClient.getAclStatus(AbfsClient.java:942)
[2025-05-22T22:10:37.801+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.services.AbfsClient.getAclStatus(AbfsClient.java:924)
[2025-05-22T22:10:37.801+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.getIsNamespaceEnabled(AzureBlobFileSystemStore.java:324)
[2025-05-22T22:10:37.801+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.getFileStatus(AzureBlobFileSystemStore.java:836)
[2025-05-22T22:10:37.801+0530] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.getFileStatus(AzureBlobFileSystem.java:507)
[2025-05-22T22:10:37.801+0530] {subprocess.py:93} INFO - 	... 18 more
[2025-05-22T22:10:37.801+0530] {subprocess.py:93} INFO - 
[2025-05-22T22:10:37.874+0530] {subprocess.py:93} INFO - 25/05/22 22:10:37 INFO SparkContext: Invoking stop() from shutdown hook
[2025-05-22T22:10:37.874+0530] {subprocess.py:93} INFO - 25/05/22 22:10:37 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-05-22T22:10:37.887+0530] {subprocess.py:93} INFO - 25/05/22 22:10:37 INFO SparkUI: Stopped Spark web UI at http://10.255.255.254:4040
[2025-05-22T22:10:37.900+0530] {subprocess.py:93} INFO - 25/05/22 22:10:37 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-05-22T22:10:37.914+0530] {subprocess.py:93} INFO - 25/05/22 22:10:37 INFO MemoryStore: MemoryStore cleared
[2025-05-22T22:10:37.914+0530] {subprocess.py:93} INFO - 25/05/22 22:10:37 INFO BlockManager: BlockManager stopped
[2025-05-22T22:10:37.920+0530] {subprocess.py:93} INFO - 25/05/22 22:10:37 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-05-22T22:10:37.924+0530] {subprocess.py:93} INFO - 25/05/22 22:10:37 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-05-22T22:10:37.932+0530] {subprocess.py:93} INFO - 25/05/22 22:10:37 INFO SparkContext: Successfully stopped SparkContext
[2025-05-22T22:10:37.932+0530] {subprocess.py:93} INFO - 25/05/22 22:10:37 INFO ShutdownHookManager: Shutdown hook called
[2025-05-22T22:10:37.933+0530] {subprocess.py:93} INFO - 25/05/22 22:10:37 INFO ShutdownHookManager: Deleting directory /tmp/spark-a3286002-8abe-48cd-ae34-3978693c6db9/pyspark-949834d5-811d-4e29-b511-1152c65b2316
[2025-05-22T22:10:37.937+0530] {subprocess.py:93} INFO - 25/05/22 22:10:37 INFO ShutdownHookManager: Deleting directory /tmp/spark-a3286002-8abe-48cd-ae34-3978693c6db9
[2025-05-22T22:10:37.940+0530] {subprocess.py:93} INFO - 25/05/22 22:10:37 INFO ShutdownHookManager: Deleting directory /tmp/spark-e5da9fb6-ba5b-4813-99b2-3e83d09f1fa0
[2025-05-22T22:10:38.007+0530] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-22T22:10:38.013+0530] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-22T22:10:38.017+0530] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=nyc_taxi_etl, task_id=transform_and_load, run_id=manual__2025-05-22T16:40:25.210508+00:00, execution_date=20250522T164025, start_date=20250522T164031, end_date=20250522T164038
[2025-05-22T22:10:38.027+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-22T22:10:38.028+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 161 for task transform_and_load (Bash command failed. The command returned a non-zero exit code 1.; 15967)
Traceback (most recent call last):
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-22T22:10:38.075+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-22T22:10:38.082+0530] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-22T22:10:38.083+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
