[2025-05-21T00:22:58.659+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T00:22:58.668+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_sync_dag.trigger_airbyte_sync manual__2025-05-20T18:52:55.021832+00:00 [queued]>
[2025-05-21T00:22:58.674+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_sync_dag.trigger_airbyte_sync manual__2025-05-20T18:52:55.021832+00:00 [queued]>
[2025-05-21T00:22:58.674+0530] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-21T00:22:58.688+0530] {taskinstance.py:2888} INFO - Executing <Task(AirbyteTriggerSyncOperator): trigger_airbyte_sync> on 2025-05-20 18:52:55.021832+00:00
[2025-05-21T00:22:58.690+0530] {standard_task_runner.py:72} INFO - Started process 8474 to run task
[2025-05-21T00:22:58.692+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'airbyte_sync_dag', 'trigger_airbyte_sync', 'manual__2025-05-20T18:52:55.021832+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/airbyte_dag.py', '--cfg-path', '/tmp/tmp_8b4zawz']
[2025-05-21T00:22:58.694+0530] {standard_task_runner.py:105} INFO - Job 89: Subtask trigger_airbyte_sync
[2025-05-21T00:22:58.723+0530] {task_command.py:467} INFO - Running <TaskInstance: airbyte_sync_dag.trigger_airbyte_sync manual__2025-05-20T18:52:55.021832+00:00 [running]> on host Voldemort.
[2025-05-21T00:22:58.766+0530] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airbyte_sync_dag' AIRFLOW_CTX_TASK_ID='trigger_airbyte_sync' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T18:52:55.021832+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T18:52:55.021832+00:00'
[2025-05-21T00:22:58.767+0530] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-21T00:22:58.796+0530] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/operators/airbyte.py", line 83, in execute
    hook = AirbyteHook(airbyte_conn_id=self.airbyte_conn_id, api_version=self.api_version)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 55, in __init__
    self.conn = self.get_conn_params(self.airbyte_conn_id)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 59, in get_conn_params
    conn = self.get_connection(conn_id)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `30a747b2-d666-4b42-86ed-a3b0b49a1bf4` isn't defined
[2025-05-21T00:22:58.801+0530] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=airbyte_sync_dag, task_id=trigger_airbyte_sync, run_id=manual__2025-05-20T18:52:55.021832+00:00, execution_date=20250520T185255, start_date=20250520T185258, end_date=20250520T185258
[2025-05-21T00:22:58.811+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-21T00:22:58.811+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 89 for task trigger_airbyte_sync (The conn_id `30a747b2-d666-4b42-86ed-a3b0b49a1bf4` isn't defined; 8474)
Traceback (most recent call last):
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/operators/airbyte.py", line 83, in execute
    hook = AirbyteHook(airbyte_conn_id=self.airbyte_conn_id, api_version=self.api_version)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 55, in __init__
    self.conn = self.get_conn_params(self.airbyte_conn_id)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 59, in get_conn_params
    conn = self.get_connection(conn_id)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `30a747b2-d666-4b42-86ed-a3b0b49a1bf4` isn't defined
[2025-05-21T00:22:58.825+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-21T00:22:58.841+0530] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T00:22:58.846+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
