[2025-05-21T20:04:34.670+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T20:04:34.684+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_sync_dag.wait_for_airbyte_sync manual__2025-05-21T14:33:10.627142+00:00 [queued]>
[2025-05-21T20:04:34.690+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_sync_dag.wait_for_airbyte_sync manual__2025-05-21T14:33:10.627142+00:00 [queued]>
[2025-05-21T20:04:34.691+0530] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-21T20:04:34.702+0530] {taskinstance.py:2888} INFO - Executing <Task(AirbyteJobSensor): wait_for_airbyte_sync> on 2025-05-21 14:33:10.627142+00:00
[2025-05-21T20:04:34.705+0530] {standard_task_runner.py:72} INFO - Started process 96296 to run task
[2025-05-21T20:04:34.707+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'airbyte_sync_dag', 'wait_for_airbyte_sync', 'manual__2025-05-21T14:33:10.627142+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/airbyte_dag.py', '--cfg-path', '/tmp/tmpgcwltp09']
[2025-05-21T20:04:34.707+0530] {standard_task_runner.py:105} INFO - Job 102: Subtask wait_for_airbyte_sync
[2025-05-21T20:04:34.733+0530] {task_command.py:467} INFO - Running <TaskInstance: airbyte_sync_dag.wait_for_airbyte_sync manual__2025-05-21T14:33:10.627142+00:00 [running]> on host Voldemort.
[2025-05-21T20:04:34.781+0530] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airbyte_sync_dag' AIRFLOW_CTX_TASK_ID='wait_for_airbyte_sync' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T14:33:10.627142+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T14:33:10.627142+00:00'
[2025-05-21T20:04:34.782+0530] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-21T20:04:34.803+0530] {baseoperator.py:405} WARNING - AirbyteJobSensor.execute cannot be called outside TaskInstance!
[2025-05-21T20:04:34.807+0530] {base.py:84} INFO - Retrieving connection 'airbyte_cloud'
[2025-05-21T20:04:35.555+0530] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 101, in get_job_details
    get_job_res = self.airbyte_api.jobs.get_job(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airbyte_api/jobs.py", line 179, in get_job
    raise errors.SDKError('API error occurred', http_res.status_code, http_res.text, http_res)
airbyte_api.errors.sdkerror.SDKError: API error occurred: Status 400
{"message":"Bad Request","_embedded":{"errors":[{"message":"Failed to convert argument [jobId] for value [{jobId}] due to: For input string: \"{jobId}\"","path":"/jobId","_embedded":{},"_links":{}}]},"_links":{"self":{"href":"/api/public/v1/jobs/%7BjobId%7D","templated":false}}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 96, in execute
    super().execute(context)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/sensors/base.py", line 306, in execute
    raise e
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/sensors/base.py", line 286, in execute
    poke_return = self.poke(context)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 77, in poke
    job = hook.get_job_details(job_id=self.airbyte_job_id)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 108, in get_job_details
    raise AirflowException(e)
airflow.exceptions.AirflowException: API error occurred: Status 400
{"message":"Bad Request","_embedded":{"errors":[{"message":"Failed to convert argument [jobId] for value [{jobId}] due to: For input string: \"{jobId}\"","path":"/jobId","_embedded":{},"_links":{}}]},"_links":{"self":{"href":"/api/public/v1/jobs/%7BjobId%7D","templated":false}}}
[2025-05-21T20:04:35.560+0530] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=airbyte_sync_dag, task_id=wait_for_airbyte_sync, run_id=manual__2025-05-21T14:33:10.627142+00:00, execution_date=20250521T143310, start_date=20250521T143434, end_date=20250521T143435
[2025-05-21T20:04:35.570+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-21T20:04:35.570+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 102 for task wait_for_airbyte_sync (API error occurred: Status 400
{"message":"Bad Request","_embedded":{"errors":[{"message":"Failed to convert argument [jobId] for value [{jobId}] due to: For input string: \"{jobId}\"","path":"/jobId","_embedded":{},"_links":{}}]},"_links":{"self":{"href":"/api/public/v1/jobs/%7BjobId%7D","templated":false}}}; 96296)
Traceback (most recent call last):
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 101, in get_job_details
    get_job_res = self.airbyte_api.jobs.get_job(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airbyte_api/jobs.py", line 179, in get_job
    raise errors.SDKError('API error occurred', http_res.status_code, http_res.text, http_res)
airbyte_api.errors.sdkerror.SDKError: API error occurred: Status 400
{"message":"Bad Request","_embedded":{"errors":[{"message":"Failed to convert argument [jobId] for value [{jobId}] due to: For input string: \"{jobId}\"","path":"/jobId","_embedded":{},"_links":{}}]},"_links":{"self":{"href":"/api/public/v1/jobs/%7BjobId%7D","templated":false}}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 96, in execute
    super().execute(context)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/sensors/base.py", line 306, in execute
    raise e
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/sensors/base.py", line 286, in execute
    poke_return = self.poke(context)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 77, in poke
    job = hook.get_job_details(job_id=self.airbyte_job_id)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 108, in get_job_details
    raise AirflowException(e)
airflow.exceptions.AirflowException: API error occurred: Status 400
{"message":"Bad Request","_embedded":{"errors":[{"message":"Failed to convert argument [jobId] for value [{jobId}] due to: For input string: \"{jobId}\"","path":"/jobId","_embedded":{},"_links":{}}]},"_links":{"self":{"href":"/api/public/v1/jobs/%7BjobId%7D","templated":false}}}
[2025-05-21T20:04:35.601+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-21T20:04:35.610+0530] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T20:04:35.611+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
