[2025-05-21T20:07:19.640+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T20:07:19.647+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_sync_dag.trigger_airbyte_sync manual__2025-05-21T14:37:15.236743+00:00 [queued]>
[2025-05-21T20:07:19.652+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_sync_dag.trigger_airbyte_sync manual__2025-05-21T14:37:15.236743+00:00 [queued]>
[2025-05-21T20:07:19.652+0530] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-21T20:07:19.664+0530] {taskinstance.py:2888} INFO - Executing <Task(AirbyteTriggerSyncOperator): trigger_airbyte_sync> on 2025-05-21 14:37:15.236743+00:00
[2025-05-21T20:07:19.666+0530] {standard_task_runner.py:72} INFO - Started process 96977 to run task
[2025-05-21T20:07:19.669+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'airbyte_sync_dag', 'trigger_airbyte_sync', 'manual__2025-05-21T14:37:15.236743+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/airbyte_dag.py', '--cfg-path', '/tmp/tmp4c5uq51j']
[2025-05-21T20:07:19.670+0530] {standard_task_runner.py:105} INFO - Job 103: Subtask trigger_airbyte_sync
[2025-05-21T20:07:19.698+0530] {task_command.py:467} INFO - Running <TaskInstance: airbyte_sync_dag.trigger_airbyte_sync manual__2025-05-21T14:37:15.236743+00:00 [running]> on host Voldemort.
[2025-05-21T20:07:19.744+0530] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airbyte_sync_dag' AIRFLOW_CTX_TASK_ID='trigger_airbyte_sync' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T14:37:15.236743+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T14:37:15.236743+00:00'
[2025-05-21T20:07:19.745+0530] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-21T20:07:19.771+0530] {base.py:84} INFO - Retrieving connection 'airbyte_cloud'
[2025-05-21T20:07:22.374+0530] {airbyte.py:89} INFO - Job 37164471 was submitted to Airbyte Server
[2025-05-21T20:08:01.106+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-21T20:08:01.108+0530] {process_utils.py:132} INFO - Sending Signals.SIGTERM to group 96977. PIDs of all processes in the group: [96977]
[2025-05-21T20:08:01.108+0530] {process_utils.py:87} INFO - Sending the signal Signals.SIGTERM to group 96977
[2025-05-21T20:08:01.108+0530] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-21T20:08:01.111+0530] {base.py:84} INFO - Retrieving connection 'airbyte_cloud'
[2025-05-21T20:08:01.111+0530] {airbyte.py:138} INFO - on_kill: cancel the airbyte Job 37164471
[2025-05-21T20:08:03.069+0530] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/operators/airbyte.py", line 96, in execute
    hook.wait_for_job(job_id=self.job_id, wait_seconds=self.wait_seconds, timeout=self.timeout)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 135, in wait_for_job
    time.sleep(wait_seconds)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-05-21T20:08:03.076+0530] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=airbyte_sync_dag, task_id=trigger_airbyte_sync, run_id=manual__2025-05-21T14:37:15.236743+00:00, execution_date=20250521T143715, start_date=20250521T143719, end_date=20250521T143803
[2025-05-21T20:08:03.085+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-21T20:08:04.032+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T20:08:04.037+0530] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: airbyte_sync_dag.trigger_airbyte_sync manual__2025-05-21T14:37:15.236743+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-05-21T20:08:04.041+0530] {local_task_job_runner.py:166} INFO - Task is not able to be run
