[2025-05-23T20:10:01.679+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-23T20:10:01.686+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_sync_dag.trigger_airbyte_sync manual__2025-05-23T14:39:57.396437+00:00 [queued]>
[2025-05-23T20:10:01.691+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_sync_dag.trigger_airbyte_sync manual__2025-05-23T14:39:57.396437+00:00 [queued]>
[2025-05-23T20:10:01.692+0530] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-23T20:10:01.703+0530] {taskinstance.py:2888} INFO - Executing <Task(AirbyteTriggerSyncOperator): trigger_airbyte_sync> on 2025-05-23 14:39:57.396437+00:00
[2025-05-23T20:10:01.706+0530] {standard_task_runner.py:72} INFO - Started process 100078 to run task
[2025-05-23T20:10:01.708+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'airbyte_sync_dag', 'trigger_airbyte_sync', 'manual__2025-05-23T14:39:57.396437+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/airbyte_dag.py', '--cfg-path', '/tmp/tmpieukk8zd']
[2025-05-23T20:10:01.709+0530] {standard_task_runner.py:105} INFO - Job 210: Subtask trigger_airbyte_sync
[2025-05-23T20:10:01.730+0530] {task_command.py:467} INFO - Running <TaskInstance: airbyte_sync_dag.trigger_airbyte_sync manual__2025-05-23T14:39:57.396437+00:00 [running]> on host Voldemort.
[2025-05-23T20:10:01.781+0530] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airbyte_sync_dag' AIRFLOW_CTX_TASK_ID='trigger_airbyte_sync' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T14:39:57.396437+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-23T14:39:57.396437+00:00'
[2025-05-23T20:10:01.781+0530] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-23T20:10:01.806+0530] {base.py:84} INFO - Retrieving connection 'airbyte_cloud'
[2025-05-23T20:10:07.846+0530] {airbyte.py:89} INFO - Job 37348460 was submitted to Airbyte Server
[2025-05-23T20:12:02.324+0530] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/operators/airbyte.py", line 96, in execute
    hook.wait_for_job(job_id=self.job_id, wait_seconds=self.wait_seconds, timeout=self.timeout)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 151, in wait_for_job
    raise AirflowException(f"Job was cancelled:\n{job}")
airflow.exceptions.AirflowException: Job was cancelled:
JobResponse(connection_id='b506b538-f525-4a80-ab7e-db858c1e7509', job_id=37348460, job_type=<JobTypeEnum.SYNC: 'sync'>, start_time='2025-05-23T14:40:09Z', status=<JobStatusEnum.CANCELLED: 'cancelled'>, bytes_synced=0, duration='PT1M53S', last_updated_at='2025-05-23T14:42:02Z', rows_synced=0)
[2025-05-23T20:12:02.329+0530] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=airbyte_sync_dag, task_id=trigger_airbyte_sync, run_id=manual__2025-05-23T14:39:57.396437+00:00, execution_date=20250523T143957, start_date=20250523T144001, end_date=20250523T144202
[2025-05-23T20:12:02.343+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-23T20:12:02.343+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 210 for task trigger_airbyte_sync (Job was cancelled:
JobResponse(connection_id='b506b538-f525-4a80-ab7e-db858c1e7509', job_id=37348460, job_type=<JobTypeEnum.SYNC: 'sync'>, start_time='2025-05-23T14:40:09Z', status=<JobStatusEnum.CANCELLED: 'cancelled'>, bytes_synced=0, duration='PT1M53S', last_updated_at='2025-05-23T14:42:02Z', rows_synced=0); 100078)
Traceback (most recent call last):
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/operators/airbyte.py", line 96, in execute
    hook.wait_for_job(job_id=self.job_id, wait_seconds=self.wait_seconds, timeout=self.timeout)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 151, in wait_for_job
    raise AirflowException(f"Job was cancelled:\n{job}")
airflow.exceptions.AirflowException: Job was cancelled:
JobResponse(connection_id='b506b538-f525-4a80-ab7e-db858c1e7509', job_id=37348460, job_type=<JobTypeEnum.SYNC: 'sync'>, start_time='2025-05-23T14:40:09Z', status=<JobStatusEnum.CANCELLED: 'cancelled'>, bytes_synced=0, duration='PT1M53S', last_updated_at='2025-05-23T14:42:02Z', rows_synced=0)
[2025-05-23T20:12:02.368+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-23T20:12:02.379+0530] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-23T20:12:02.384+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
